services:
  client:
    depends_on:
      - server

    build:
      context: ./mis_client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    environment:
      - SERVER_URL=http://server:4000
    develop:
      watch:
        - path: ./mis_client/package.json
          action: rebuild
        - path: ./mis_client/next.config.js
          action: rebuild
        - path: ./mis_client
          target: /usr/src/client
          action: sync
  server:
    depends_on:
      - redis
    env_file:
      - path: ./mis_server/.env
        required: true
    build:
      context: ./mis_server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    develop:
      watch:
        - path: ./mis_server/package.json
          action: rebuild
        - path: ./mis_server/src
          target: /usr/src/server/src
          action: sync

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"