version: '3.8'

services:
  client:
    build:
      context: ./mis_client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - server
  server:
    build:
      context: ./mis_server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"